# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  ios_build:
    # macos:
    #   xcode: "16.0.0"
    machine: true
    resource_class: bloodrainzwork/macrunner
    steps:
      - checkout
      # - run:
      #     name: Download Certificate
      #     command: |
      #       some command to download certificate
      # - run:
      #     name: Install Certificate
      #     command: |
      #       security import ./MyPrivateKey.p12 -k bobbins.keychain -P privateKeyPassword
      # - run:
      #     name: Download Provisioning profile
      #     command: |
      #       some command to download Provisioning profile
      # - run:
      #     name: Install Provisioning profile
      #     command: |
      #       sh script/installMobileProvisionFile.sh
      - run:
          name: Check HomeBrew
          command: |
            brew doctor
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f:net8.0-ios /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false 
      - store_artifacts:
          path: './Maui_Narumit/bin'
          destination: artifact-file
  android_build:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - checkout
      - run: 
          name: install android sdk
          command: |
            choco install android-sdk -y
      - run: 
          name: manage android sdk
          command: |
            "%ANDROID_HOME%\tools\bin\sdkmanager.bat --licenses" 
            sdkmanager "tools" "platform-tools" "build-tools;34.0.0" "platforms;android-34"
      - run:
          name: Install .NET SDK
          command: |
            dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet restore --inactive
            dotnet build -f:net8.0-android /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false 
      - store_artifacts:
          path: './Maui_Narumit/bin/Release/net8.0-android/com.companyname.maui_narumit-Signed.aab'
          destination: artifact-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - ios_build
      # - android_build