# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  ios_build:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run:
          name: Check HomeBrew
          command: |
            brew doctor
      - run:
          name: install java
          command: |
            brew install --cask temurin
      - run:
          name: Install Android SDK with brew
          command: |
            brew install --cask android-commandlinetools
            yes | sdkmanager "tools" "platform-tools" "build-tools;33.0.1" "platforms;android-33" "system-images;android-31;google_apis;x86_64" "extras;intel;Hardware_Accelerated_Execution_Manager"
            yes | sdkmanager --licenses
      - run:
          name: Install Android SDK with brew
          command: |
            export ANDROID_HOME=/usr/local/share/android-commandlinetools
            export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-ios
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-android
workflows:
  version: 2
  build_and_test:
    jobs:
      - ios_build