# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  ios_build:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run:
          name: Check HomeBrew
          command: |
            brew doctor
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-ios
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-android
  android_job:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - checkout
      - run: 
          name: install android sdk
          command: |
            choco install android-sdk -y
            sdkmanager --list

workflows:
  version: 2
  build_and_test:
    jobs:
      # - ios_build
      - android_job