# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  macos: circleci/macos@2.5.2
jobs:
  build:
    macos:
      xcode: 15.4.0
    environment:
      ANDROID_HOME: "/usr/local/share/android-sdk"
      ANDROID_SDK_HOME: "/usr/local/share/android-sdk"
      ANDROID_SDK_ROOT: "/usr/local/share/android-sdk"
      PATH: "$PATH:$ANDROID_HOME/tools/bin"
    steps:
      - checkout
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - run: brew install --cask dotnet-sdk --force
      - run: brew install --cask android-sdk --force
      - run: brew install --cask android-platform-tools
      - run: ls /usr/local/share
      - run: ls /Users/$USER/Library
      - run: dotnet --version
      - run: sudo dotnet workload install maui
      - run: cd Maui_Narumit
      - run: dotnet build
workflows:
  verify:
    jobs:
      - build