# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run:
          name: Check HomeBrew
          command: |
            brew doctor
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Install Android SDK
          command: |
            sudo softwareupdate --install-rosetta
            brew install --cask temurin@8
            brew install android-sdk
            android update sdk --no-ui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-ios
      - run:
          name: Build .NET MAUI Project
          command: |
            cd Maui_Narumit
            dotnet build -f net8.0-android
workflows:
  version: 2
  build_and_test:
    jobs:
      - build