# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd MyMauiApp
            dotnet build -t:Run -f net8.0-ios
workflows:
  version: 2
  build_and_test:
    jobs:
      - build