# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  macos: circleci/macos@2.5.2
jobs:
  build:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - run: brew install --cask dotnet-sdk
      - run: dotnet --version
      - run: dotnet workload install maui
      - run: cd Maui_Narumit
      - run: dotnet build Maui_Narumit.csproj
workflows:
  verify:
    jobs:
      - build